import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'
import NavbarWrapper from "@/components/NavbarWrapper";
import { UserProvider } from "@/lib/context/UserContext";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
})
export const metadata: Metadata = {
  title: "Edutech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-poppins antialiased bg-blue-500`}
      >
        <UserProvider>
        <NavbarWrapper />
        {children}
        </UserProvider>
      </body>
    </html>
  );
}